"""
Building Guide App v2 — Claude 버전
- v1 (Gemini)에서 Anthropic Claude로 마이그레이션
- 모델 선택 UI 추가 (Haiku / Sonnet / Opus)
- 응답 스트리밍 지원 (체감 속도 향상)
- 입력 검증 강화
- 최근 검색 히스토리 (세션 단위)
- 다운로드 버튼 (마크다운으로 저장)
"""

import streamlit as st
from anthropic import Anthropic
from datetime import datetime

# --- 1. API 키 로드 ---
# Streamlit Cloud의 비밀 저장소(또는 .streamlit/secrets.toml)에서 키 로드
try:
    ANTHROPIC_API_KEY = ***"ANTHROPIC_API_KEY"]
except (KeyError, FileNotFoundError):
    ANTHROPIC_API_KEY = None

# --- 2. 페이지 설정 ---
st.set_page_config(
    page_title="건물 정보 검색 (Claude)",
    page_icon="🏢",
    layout="centered",
)

st.title("🏢 건물 정보 검색")
st.caption("Powered by Anthropic Claude · v2")

# --- 3. 사이드바: 모델 선택 + 옵션 ---
with st.sidebar:
    st.header("⚙️ 설정")
    model_choice = st.selectbox(
        "모델 선택",
        options=[
            ("claude-sonnet-4-5", "Sonnet 4.5 (균형, 추천)"),
            ("claude-haiku-4-5", "Haiku 4.5 (빠름, 저렴)"),
            ("claude-opus-4-5", "Opus 4.5 (최고 품질, 느림)"),
        ],
        format_func=lambda x: x[1],
        index=0,
    )
    selected_model = model_choice[0]

    max_tokens = st.slider("최대 응답 길이 (토큰)", 512, 4096, 2048, step=256)

    use_streaming = st.toggle("스트리밍 응답", value=True, help="응답이 한 글자씩 실시간으로 나옵니다")

    st.divider()
    st.caption("v1 (Gemini)는 `building-guide-app-v1.py`에 보존됨")

# --- 4. 메인 입력 ---
st.subheader("도시와 건물 이름을 입력하세요")

col1, col2 = st.columns(2)
with col1:
    city = st.text_input("도시", placeholder="예: 서울, 파리, 뉴욕")
with col2:
    building_name = st.text_input("건물 이름", placeholder="예: 63빌딩, 에펠탑")

# --- 5. 시스템 프롬프트 ---
SYSTEM_PROMPT = """너는 전문 건축 가이드야. 사용자가 도시와 건물을 입력하면 해당 건물을 설명해줘.

반드시 '한국어'로 친절하고 자세하게 답변해야 해.

답변 구조 (마크다운으로):
## 1. 한 줄 요약
간결하게.

## 2. 상세 정보
- 완공 연도:
- 설계자/건축가:
- 건축 양식:
- 높이/규모:
- 용도:

## 3. 건축적 특징
주요 디자인 요소, 구조적 특징, 사용된 재료 등.

## 4. 역사적/문화적 의의
왜 중요한 건물인지, 어떤 의미를 가지는지.

## 5. 방문 팁
실용 정보 (개방 여부, 주변 볼거리, 사진 명소 등).

만약 입력이 모호하거나 실재하지 않는 건물이면, 정직하게 "확인 어려움"이라고 말하고 가능한 범위에서 답변해줘.
정보의 확신도가 낮은 부분은 "추정", "확인 필요" 등으로 명시해."""

# --- 6. 결과 출력 ---
def render_streaming_response(client, model, system, user_msg, max_tok):
    """스트리밍 응답을 렌더링하고 전체 텍스트를 반환."""
    placeholder = st.empty()
    full_text = ""
    with client.messages.stream(
        model=model,
        max_tokens=max_tok,
        system=system,
        messages=[{"role": "user", "content": user_msg}],
    ) as stream:
        for text in stream.text_stream:
            full_text += text
            placeholder.markdown(full_text + "▌")
    placeholder.markdown(full_text)
    return full_text

def render_full_response(client, model, system, user_msg, max_tok):
    """일반(non-streaming) 응답."""
    response = client.messages.create(
        model=model,
        max_tokens=max_tok,
        system=system,
        messages=[{"role": "user", "content": user_msg}],
    )
    text = response.content[0].text
    st.markdown(text)
    return text

# --- 7. 실행 ---
if st.button("🔍 정보 가져오기", type="primary"):
    # 입력 검증
    if not city.strip() or not building_name.strip():
        st.warning("⚠️ 도시와 건물 이름을 모두 입력해 주세요.")
    elif not ANTHROPIC_API_KEY:
        ***"❌ API 키가 설정되지 않았습니다. `.streamlit/secrets.toml` 또는 Streamlit Cloud secrets에 `ANTHROPIC_API_KEY`를 등록해주세요.")
    else:
        try:
            client = Anthropic(api_key=ANTHROPIC_API_KEY)
            user_prompt = f"도시: {city.strip()}, 건물 이름: {building_name.strip()}"

            st.markdown("---")
            st.markdown(f"### 📍 {building_name.strip()} ({city.strip()})")

            with st.spinner(f"Claude ({selected_model})가 정보를 분석 중..."):
                if use_streaming:
                    answer = render_streaming_response(
                        client, selected_model, SYSTEM_PROMPT, user_prompt, max_tokens
                    )
                else:
                    answer = render_full_response(
                        client, selected_model, SYSTEM_PROMPT, user_prompt, max_tokens
                    )

            # 다운로드 버튼
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            md_content = f"# {building_name.strip()} ({city.strip()})\n\n{answer}\n\n---\n_Generated by Claude {selected_model} on {timestamp}_"
            st.download_button(
                label="📥 마크다운으로 저장",
                data=md_content,
                file_name=f"{building_name.strip()}_{city.strip()}_{timestamp}.md",
                mime="text/markdown",
            )

            # 히스토리 저장
            if "history" not in st.session_state:
                st.session_state.history = []
            st.session_state.history.insert(0, {
                "city": city.strip(),
                "building": building_name.strip(),
                "time": datetime.now().strftime("%H:%M:%S"),
                "model": selected_model,
            })
            st.session_state.history = st.session_state.history[:10]  # 최근 10개

        except Exception as e:
            ***f"오류 발생: {e}")
            st.caption("API 키, 네트워크, 모델 ID를 확인해보세요.")

# --- 8. 사이드바 히스토리 ---
if "history" in st.session_state and st.session_state.history:
    with st.sidebar:
        st.divider()
        st.subheader("🕘 최근 검색")
        for h in st.session_state.history:
            st.caption(f"`{h['time']}` {h['building']} ({h['city']}) — _{h['model'].split('-')[1]}_")
